sudo: required

language: c

install:
  - sudo add-apt-repository ppa:kubuntu-ppa/backports -y
  - sudo apt-get update
  - sudo apt-get install --only-upgrade cmake

script:
  - mkdir _build
  - cd _build
  - cmake ..
  - make
